version: "0.2"
ignorePaths:
  - .gitignore
dictionaryDefinitions: []
dictionaries:
  - pt-br
words:
  - feld
  - iconify
  - inlang
  - osts
  - paraglide
  - pytest
  - SinaNova
ignoreWords: []
import: []
